export enum ResponseError {
	ERROR_FORBIDDEN = 'ERROR_FORBIDDEN',
	ERROR_UNAUTHORIZED = 'ERROR_UNAUTHORIZED',
	ERROR_SERVER = 'ERROR_SERVER',
	ERROR_DATA_SUBMIT_IS_INVALID = 'ERROR_DATA_SUBMIT_IS_INVALID',
}
